server:
  port: 9010

spring:
  application:
    name: "email"
  cloud:
    function:
      definition: email;otp
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: "email-consumer-group"
          content-type: application/json
        otp-in-0:
          destination: send-otp
          group: "otp-consumer-group"
          content-type: application/json
#      kafka:
#        binder:
#          brokers: localhost:9092

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


